"""added artist id to cw

Revision ID: 36ad21b6bf82
Revises: 8e3ebdeb2efd
Create Date: 2024-01-27 19:29:42.795389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ad21b6bf82'
down_revision = '8e3ebdeb2efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_creative_works_table_artist_id_artist_table'), 'artist_table', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_creative_works_table_artist_id_artist_table'), type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
