"""added compensation to requests

Revision ID: 5bcb31c528a2
Revises: 36ad21b6bf82
Create Date: 2024-01-28 23:48:04.593487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcb31c528a2'
down_revision = '36ad21b6bf82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('compensation', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.drop_column('compensation')

    # ### end Alembic commands ###
