"""Initial Migration

Revision ID: 8e3ebdeb2efd
Revises: 
Create Date: 2024-01-27 19:21:02.241133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3ebdeb2efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artist_table'))
    )
    op.create_table('business_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_table'))
    )
    op.create_table('creative_works_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creative_works_table'))
    )
    op.create_table('request_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_table.id'], name=op.f('fk_request_table_artist_id_artist_table')),
    sa.ForeignKeyConstraint(['business_id'], ['business_table.id'], name=op.f('fk_request_table_business_id_business_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_table')
    op.drop_table('creative_works_table')
    op.drop_table('business_table')
    op.drop_table('artist_table')
    # ### end Alembic commands ###
