"""updated creative works file_url --> file

Revision ID: aa5dac600ce8
Revises: 6ca5eae632c2
Create Date: 2024-02-04 05:38:08.352896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5dac600ce8'
down_revision = '6ca5eae632c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(), nullable=True))
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creative_works_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('file')

    # ### end Alembic commands ###
