"""added contact info columns to artist and business

Revision ID: bcfd338e612d
Revises: 5bcb31c528a2
Create Date: 2024-01-30 15:46:21.144858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfd338e612d'
down_revision = '5bcb31c528a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))

    with op.batch_alter_table('business_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))
        batch_op.drop_column('location')

    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_table', schema=None) as batch_op:
        batch_op.alter_column('date_created',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    with op.batch_alter_table('business_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')

    with op.batch_alter_table('artist_table', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
