"""added Bid class/table

Revision ID: d814f3638f8e
Revises: 3c4f300c3ece
Create Date: 2024-01-31 11:00:44.858737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd814f3638f8e'
down_revision = '3c4f300c3ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_table.id'], name=op.f('fk_bids_table_artist_id_artist_table')),
    sa.ForeignKeyConstraint(['request_id'], ['request_table.id'], name=op.f('fk_bids_table_request_id_request_table')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bids_table'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bids_table')
    # ### end Alembic commands ###
